/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bench4q_monitor_performance_windows_LogicalDiskMonitor */

#ifndef _Included_org_bench4q_monitor_performance_windows_LogicalDiskMonitor
#define _Included_org_bench4q_monitor_performance_windows_LogicalDiskMonitor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getInstances
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getInstances
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getCounterList
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getCounterList
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getFreeSpacePercent
	* Signature: (Ljava/lang/String;)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getFreeSpacePercent
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getFreeMegabytes
	* Signature: (Ljava/lang/String;)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getFreeMegabytes
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getCurrentDiskQueueLength
	* Signature: (Ljava/lang/String;)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getCurrentDiskQueueLength
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskReadTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskReadTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskReadQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskReadQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskWriteTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskWriteTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskWriteQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskWriteQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskTransferTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskTransferTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskReadTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskReadTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskWriteTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskWriteTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskTransfersPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskTransfersPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskReadsPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskReadsPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskWritesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskWritesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskReadBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskReadBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getDiskWriteBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getDiskWriteBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskBytesPerTransfer
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskBytesPerTransfer
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskBytesPerRead
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskBytesPerRead
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getAverageDiskBytesPerWrite
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getAverageDiskBytesPerWrite
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getIdleTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getIdleTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_LogicalDiskMonitor
	* Method:    getSplitIOPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_LogicalDiskMonitor_getSplitIOPerSecond
		(JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
