/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bench4q_monitor_performance_windows_MemoryMonitor */

#ifndef _Included_org_bench4q_monitor_performance_windows_MemoryMonitor
#define _Included_org_bench4q_monitor_performance_windows_MemoryMonitor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCounterList
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCounterList
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPageFaultsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPageFaultsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getAvailableBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getAvailableBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCommittedBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCommittedBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCommitLimit
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCommitLimit
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getWriteCopiesPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getWriteCopiesPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getTransitionFaultsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getTransitionFaultsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCacheFaultsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCacheFaultsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getDemandZeroFaultsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getDemandZeroFaultsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPagesPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPagesPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPagesInputPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPagesInputPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPageReadsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPageReadsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPagesOutputPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPagesOutputPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPoolPagedBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPoolPagedBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPoolNonpagedBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPoolNonpagedBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPageWritesPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPageWritesPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPoolPagedAllocs
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPoolPagedAllocs
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPoolNonpagedAllocs
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPoolNonpagedAllocs
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getFreeSystemPageTableEntries
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getFreeSystemPageTableEntries
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCacheBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCacheBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCacheBytesPeak
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCacheBytesPeak
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getPoolPagedResidentBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getPoolPagedResidentBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getSystemCodeTotalBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getSystemCodeTotalBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getSystemCodeResidentBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getSystemCodeResidentBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getSystemDriverTotalBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getSystemDriverTotalBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getSystemDriverResidentBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getSystemDriverResidentBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getSystemCacheResidentBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getSystemCacheResidentBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getCommittedBytesInUsePercent
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getCommittedBytesInUsePercent
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getAvailableKiloBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getAvailableKiloBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getAvailableMegaBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getAvailableMegaBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getTransitionPagesRepurposedPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getTransitionPagesRepurposedPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getFreeAndZeroPageListBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getFreeAndZeroPageListBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getModifiedPageListBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getModifiedPageListBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getStandbyCacheReserveBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getStandbyCacheReserveBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getStandbyCacheNormalPriorityBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getStandbyCacheNormalPriorityBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getStandbyCacheCoreBytes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getStandbyCacheCoreBytes
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_MemoryMonitor
	* Method:    getLongTermAverageStandbyCacheLifetimes
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_MemoryMonitor_getLongTermAverageStandbyCacheLifetimes
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
