/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bench4q_monitor_performance_windows_PhysicalDiskMonitor */

#ifndef _Included_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
#define _Included_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getInstances
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getInstances
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getCounterList
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getCounterList
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getCurrentDiskQueueLength
	* Signature: (Ljava/lang/String;)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getCurrentDiskQueueLength
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskReadTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskReadTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskReadQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskReadQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskWriteTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskWriteTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskWriteQueueLength
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskWriteQueueLength
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskTransferTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskTransferTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskReadTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskReadTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskWriteTimeInSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskWriteTimeInSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskTransfersPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskTransfersPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskReadsPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskReadsPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskWritesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskWritesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskReadBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskReadBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getDiskWriteBytesPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getDiskWriteBytesPerSecond
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskBytesPerTransfer
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskBytesPerTransfer
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskBytesPerRead
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskBytesPerRead
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getAverageDiskBytesPerWrite
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getAverageDiskBytesPerWrite
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getIdleTimePercent
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getIdleTimePercent
		(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_PhysicalDiskMonitor
	* Method:    getSplitIOPerSecond
	* Signature: (Ljava/lang/String;I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_PhysicalDiskMonitor_getSplitIOPerSecond
		(JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
