/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bench4q_monitor_performance_windows_TCPv4Monitor */

#ifndef _Included_org_bench4q_monitor_performance_windows_TCPv4Monitor
#define _Included_org_bench4q_monitor_performance_windows_TCPv4Monitor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getCounterList
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getCounterList
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getSegmentsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getSegmentsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getConnectionsEstablished
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getConnectionsEstablished
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getConnectionsActive
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getConnectionsActive
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getConnectionsPassive
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getConnectionsPassive
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getConnectionFailures
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getConnectionFailures
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getConnectionsReset
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getConnectionsReset
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getSegmentsReceivedPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getSegmentsReceivedPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getSegmentsSentPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getSegmentsSentPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_TCPv4Monitor
	* Method:    getSegmentsRetransmittedPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_TCPv4Monitor_getSegmentsRetransmittedPerSecond
		(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
