/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bench4q_monitor_performance_windows_UDPv4Monitor */

#ifndef _Included_org_bench4q_monitor_performance_windows_UDPv4Monitor
#define _Included_org_bench4q_monitor_performance_windows_UDPv4Monitor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getCounterList
	* Signature: ()[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getCounterList
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getDatagramsPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getDatagramsPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getDatagramsReceivedPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getDatagramsReceivedPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getDatagramsNoPortPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getDatagramsNoPortPerSecond
		(JNIEnv *, jobject, jint);

	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getDatagramsReceivedErrors
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getDatagramsReceivedErrors
		(JNIEnv *, jobject);

	/*
	* Class:     org_bench4q_monitor_performance_windows_UDPv4Monitor
	* Method:    getDatagramsSentPerSecond
	* Signature: (I)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_bench4q_monitor_performance_windows_UDPv4Monitor_getDatagramsSentPerSecond
		(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
